/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package StudentsRecordSystemConsole;

public class App {
    public static void main(String[] args) {
        new Main("database.db").driverCode();
    }
}
